# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

# import toupper_pb2 as toupper__pb2
from proto import toupper_pb2 as toupper__pb2


class ToUpperStub(object):
  """The service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Upper = channel.unary_unary(
        '/proto.ToUpper/Upper',
        request_serializer=toupper__pb2.UpperRequest.SerializeToString,
        response_deserializer=toupper__pb2.UpperReply.FromString,
        )


class ToUpperServicer(object):
  """The service definition.
  """

  def Upper(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ToUpperServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Upper': grpc.unary_unary_rpc_method_handler(
          servicer.Upper,
          request_deserializer=toupper__pb2.UpperRequest.FromString,
          response_serializer=toupper__pb2.UpperReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.ToUpper', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
